/*
 * BIMROCKET
 *
 * Copyright (C) 2021, Ajuntament de Sant Feliu de Llobregat
 *
 * This program is licensed and may be used, modified and redistributed under
 * the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European
 * Commission.
 *
 * Alternatively, you may redistribute and/or modify this program under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either  version 3 of the License, or (at your option)
 * any later version.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the licenses for the specific language governing permissions, limitations
 * and more details.
 *
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along
 * with this program; if not, you may find them at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * http://www.gnu.org/licenses/
 * and
 * https://www.gnu.org/licenses/lgpl.txt
 */

package org.bimrocket.generators;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import org.bimrocket.express.ExpressAttribute;
import org.bimrocket.express.ExpressCollection;
import org.bimrocket.express.ExpressConstant;
import org.bimrocket.express.ExpressDefinedType;
import org.bimrocket.express.ExpressEntity;
import org.bimrocket.express.ExpressEnumeration;
import org.bimrocket.express.ExpressInverseAttribute;
import org.bimrocket.express.ExpressNamedType;
import org.bimrocket.express.ExpressPrimitive;
import org.bimrocket.express.ExpressSchema;
import org.bimrocket.express.ExpressSelect;
import org.bimrocket.express.ExpressType;
import org.bimrocket.express.io.ExpressLoader;

/**
 *
 * @author realor
 */
public class IfcJavascriptClassesGenerator
{
  private PrintWriter writer;
  private String schemaVersion = "IFC2X3";
  private final HashSet<String> generatedClasses = new HashSet<>();

  public String getSchemaVersion()
  {
    return schemaVersion;
  }

  public void setSchemaVersion(String schemaVersion)
  {
    this.schemaVersion = schemaVersion;
  }

  public void generateClasses(String schemaFileName, File outputFile)
    throws IOException
  {
    generatedClasses.clear();

    ExpressLoader loader = new ExpressLoader();
    ExpressSchema schema = loader.load(schemaFileName);

    writer = new PrintWriter(outputFile, "UTF-8");
    try
    {
      writeHeader(schemaFileName);
      List<ExpressEntity> entities = schema.getNamedTypes(ExpressEntity.class);
      for (ExpressEntity entity : entities)
      {
        writeEntity(entity);
      }
      writer.println();

      List<ExpressDefinedType> definedTypes =
        schema.getNamedTypes(ExpressDefinedType.class);
      for (ExpressDefinedType definedType : definedTypes)
      {
        writeDefinedType(definedType);
      }
      writer.println();

      List<ExpressSelect> selects =
        schema.getNamedTypes(ExpressSelect.class);
      for (ExpressSelect select : selects)
      {
        writeSelect(select);
      }
      writer.println();


      List<ExpressEnumeration> enumerations =
        schema.getNamedTypes(ExpressEnumeration.class);
      for (ExpressEnumeration enumeration : enumerations)
      {
        writeEnumeration(enumeration);
      }
      writer.println();

      writeFooter();
    }
    finally
    {
      writer.close();
    }
  }

  protected void writeHeader(String schemaFileName)
  {
    Date date = new Date();
    writer.println("/*");
    writer.println("  Autogenerated IFC classes");
    writer.println("  Express schema file: " + schemaFileName);
    writer.println("  Schema version: " + schemaVersion);
    writer.println("  Generation date: " + date);
    writer.println("*/");
    writer.println();

    writer.println("import { registerIfcClass } " +
      "from \"../IFC.js\";");
    writer.println();

    writer.println("class SchemaBase");
    writer.println("{");
    writer.println("  static schemaName = \"" + schemaVersion + "\";");
    writer.println("  static get schema()");
    writer.println("  {");
    writer.println("    return IFC.SCHEMAS[this.schemaName];");
    writer.println("  }");
    writer.println("};");
    writer.println();

    writer.println("class Entity extends SchemaBase");
    writer.println("{");
    writer.println("  static isEntity = true;");
    writer.println();
    writer.println("  _id = null;");
    writer.println("};");
    writer.println();

    writer.println("class DefinedType extends SchemaBase");
    writer.println("{");
    writer.println("  static isDefinedType = true;");
    writer.println("};");
    writer.println();

    writer.println("class Select extends SchemaBase");
    writer.println("{");
    writer.println("  static isSelect = true;");
    writer.println("};");
    writer.println();

    writer.println("class Enumeration extends SchemaBase");
    writer.println("{");
    writer.println("  static isEnumeration = true;");
    writer.println("};");
    writer.println();
  }

  protected void writeFooter()
  {
  }

  protected void writeEntity(ExpressEntity entity)
  {
    if (generatedClasses.contains(entity.getTypeName())) return;

    ExpressEntity superEntity = entity.getSuperEntity();

    // write super entity first
    if (superEntity != null)
    {
      writeEntity(superEntity);
    }

    // write this entity
    writer.print("class " + entity.getTypeName());
    writer.println(" extends " + (superEntity == null ?
      "Entity" : superEntity.getTypeName()));
    writer.println("{");

    List<ExpressAttribute> attributes = entity.getAttributes();
    if (!attributes.isEmpty())
    {
      for (ExpressAttribute attribute : attributes)
      {
        writer.print("  static " + attribute.getName() + " = ");
        writeType(attribute.getType());
        writer.println(";");
        writer.println("  " + attribute.getName() + " = null;");
      }
    }

    List<ExpressInverseAttribute> inverseAttributes =
      entity.getInverseAttributes();
    if (!inverseAttributes.isEmpty())
    {
      for (ExpressInverseAttribute inverseAttribute : inverseAttributes)
      {
        writer.print("  static _" + inverseAttribute.getName() + " = ");
        writeType(inverseAttribute.getType());
        writer.print("; // ");
        writer.println(" FOR " + inverseAttribute.getForAttribute());
        writer.println("  _" + inverseAttribute.getName() + " = null;");
      }
      writer.println();
    }

    writer.println("};");
    writer.println("registerIfcClass(" + entity.getTypeName() + ");");
    writer.println();
    generatedClasses.add(entity.getTypeName());
  }

  protected void writeDefinedType(ExpressDefinedType type)
  {
    ExpressType definition = type.getDefinition();

    writer.println("class " + type.getTypeName() + " extends DefinedType");
    writer.println("{");
    writer.print("  static Value = ");
    writeType(definition);
    writer.println(";");
    writer.println("  Value = null;");
    writer.println("};");
    writer.println("registerIfcClass(" + type.getTypeName() + ");");
    writer.println();
  }

  protected void writeSelect(ExpressSelect type)
  {
    writer.println("class " + type.getTypeName() + " extends Select");
    writer.println("{");
    List<ExpressNamedType> options = type.getOptions();
    writer.print("  static Options = [");
    for (int i = 0; i < options.size(); i++)
    {
      if (i > 0) writer.print(", ");
      writer.print('"' + options.get(i).getTypeName() + '"');
    }
    writer.println("];");
    writer.println("};");
    writer.println("registerIfcClass(" + type.getTypeName() + ");");
    writer.println();
  }

  protected void writeEnumeration(ExpressEnumeration type)
  {
    writer.println("class " + type.getTypeName() + " extends Enumeration");
    writer.println("{");
    List<ExpressConstant> values = type.getValues();
    writer.print("  static Values = [");
    for (int i = 0; i < values.size(); i++)
    {
      if (i > 0) writer.print(", ");
      writer.print('"' + values.get(i).toString() + '"');
    }
    writer.println("];");
    writer.println("};");
    writer.println("registerIfcClass(" + type.getTypeName() + ");");
    writer.println();
  }

  protected void writeType(ExpressType type)
  {
    if (type instanceof ExpressNamedType)
    {
      ExpressNamedType namedType = (ExpressNamedType)type;
      writer.print('"' + namedType.getTypeName() + '"');
    }
    else if (type instanceof ExpressCollection)
    {
      ExpressCollection col = (ExpressCollection)type;
      writer.print("[");
      writer.print('"' + col.getTypeName() + '"');
      writer.print(", ");
      writeType(col.getItemType());
      writer.print(", ");
      writer.print(col.getMinOccurrences());
      writer.print(", ");
      writer.print(col.getMaxOccurrences());
      writer.print("]");
    }
    else if (type instanceof ExpressPrimitive)
    {
      ExpressPrimitive primitive = (ExpressPrimitive)type;
      String primType = primitive.getTypeName();
      writer.write('"' + primType + '"');
    }
  }

  public static void main(String[] args) throws IOException
  {
    if (args.length < 2)
    {
      System.out.println("Arguments: schemaFile outputFile " +
        "[-v:schemaVersion]");
    }
    else
    {
      IfcJavascriptClassesGenerator generator =
        new IfcJavascriptClassesGenerator();

      String schemaFileName = null;
      File outputFile = null;

      for (String arg : args)
      {
        if (arg.startsWith("-v:"))
        {
          generator.setSchemaVersion(arg.substring(3));
        }
        else if (schemaFileName == null)
        {
          schemaFileName = arg;
        }
        else if (outputFile == null)
        {
          outputFile = new File(arg);
        }
      }
      if (schemaFileName != null && outputFile != null)
      {
        if (outputFile.exists())
        {
          System.out.println(outputFile + " already exists.");
        }
        else
        {
          generator.generateClasses(schemaFileName, outputFile);
        }
      }
    }
  }
}
