<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.bimrocket</groupId>
    <artifactId>bimrocket</artifactId>
    <version>1.0</version>
  </parent>

  <artifactId>bimrocket-webapp</artifactId>
  <name>bimrocket-webapp</name>
  <description>bimrocket client webapp</description>
  <packaging>war</packaging>

  <properties>
    <endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.platform</groupId>
      <artifactId>jakarta.jakartaee-api</artifactId>
      <version>9.0.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.bimrocket</groupId>
      <artifactId>bimrocket-common</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.8.0</version>
    </dependency>
  </dependencies>

  <build>
    <finalName>bimrocket</finalName>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.2.1</version>
        <executions>
          <execution>
            <id>IFC4X3_ADD2_classes_generation</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>org.bimrocket.generators.IfcJavascriptClassesGenerator</mainClass>
              <arguments>
                <argument>schema:IFC4X3_ADD2</argument>
                <argument>${basedir}/src/main/webapp/platform/io/ifc/schemas/IFC4X3_ADD2.js</argument>
                <argument>-v:IFC4X3_ADD2</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>IFC4_classes_generation</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>org.bimrocket.generators.IfcJavascriptClassesGenerator</mainClass>
              <arguments>
                <argument>schema:IFC4</argument>
                <argument>${basedir}/src/main/webapp/platform/io/ifc/schemas/IFC4.js</argument>
                <argument>-v:IFC4</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>IFC2X3_classes_generation</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>org.bimrocket.generators.IfcJavascriptClassesGenerator</mainClass>
              <arguments>
                <argument>schema:IFC2X3</argument>
                <argument>${basedir}/src/main/webapp/platform/io/ifc/schemas/IFC2X3.js</argument>
                <argument>-v:IFC2X3</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>set version</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>org.bimrocket.util.BimRocketInfo</mainClass>
              <arguments>
                <argument>${basedir}/src/main/webapp/platform/ui/Application.js</argument>
                <argument>${basedir}/target/Application.js</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>pack-svg-stroke-icons</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>org.bimrocket.util.SvgSpriteGenerator</mainClass>
              <arguments>
                <argument>-normalize</argument>
                <!-- platform -->
                <argument>${basedir}/src/main/webapp/platform/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/platform/assets/icons/misc.svg</argument>
                <!-- analysis module -->
                <argument>${basedir}/src/main/webapp/modules/analysis/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/modules/analysis/assets/icons/misc.svg</argument>
                <!-- base module -->
                <argument>${basedir}/src/main/webapp/modules/base/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/modules/base/assets/icons/misc.svg</argument>
                <!-- bim module -->
                <argument>${basedir}/src/main/webapp/modules/bim/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/modules/bim/assets/icons/misc.svg</argument>
                <!-- control module -->
                <argument>${basedir}/src/main/webapp/modules/control/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/modules/control/assets/icons/misc.svg</argument>
                <!-- design module -->
                <argument>${basedir}/src/main/webapp/modules/design/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/modules/design/assets/icons/misc.svg</argument>
                <!-- gis module -->
                <argument>${basedir}/src/main/webapp/modules/gis/assets/icons/misc</argument>
                <argument>${basedir}/target/bimrocket/modules/gis/assets/icons/misc.svg</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>pack-svg-mask-icons</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>org.bimrocket.util.SvgSpriteGenerator</mainClass>
              <arguments>
                <argument>-stack</argument>
                <!-- inspector -->
                <argument>${basedir}/src/main/webapp/platform/assets/icons/inspector</argument>
                <argument>${basedir}/target/bimrocket/platform/assets/icons/inspector.svg</argument>
                <!-- file -->
                <argument>${basedir}/src/main/webapp/platform/assets/icons/file</argument>
                <argument>${basedir}/target/bimrocket/platform/assets/icons/file.svg</argument>
                <!-- outliner -->
                <argument>${basedir}/src/main/webapp/platform/assets/icons/outliner</argument>
                <argument>${basedir}/target/bimrocket/platform/assets/icons/outliner.svg</argument>
                <!-- tree -->
                <argument>${basedir}/src/main/webapp/platform/assets/icons/tree</argument>
                <argument>${basedir}/target/bimrocket/platform/assets/icons/tree.svg</argument>
                <!-- geometry -->
                <argument>${basedir}/src/main/webapp/modules/design/assets/icons/geometry</argument>
                <argument>${basedir}/target/bimrocket/modules/design/assets/icons/geometry.svg</argument>
                <!-- report -->
                <argument>${basedir}/src/main/webapp/modules/analysis/assets/icons/report</argument>
                <argument>${basedir}/target/bimrocket/modules/analysis/assets/icons/report.svg</argument>
                <!-- ifc -->
                <argument>${basedir}/src/main/webapp/modules/bim/assets/icons/ifc</argument>
                <argument>${basedir}/target/bimrocket/modules/bim/assets/icons/ifc.svg</argument>
                <!-- bsdd -->
                <argument>${basedir}/src/main/webapp/modules/bim/assets/icons/bsdd</argument>
                <argument>${basedir}/target/bimrocket/modules/bim/assets/icons/bsdd.svg</argument>
                <!-- ifc-inspector -->
                <argument>${basedir}/src/main/webapp/modules/bim/assets/icons/inspector</argument>
                <argument>${basedir}/target/bimrocket/modules/bim/assets/icons/inspector.svg</argument>
                <!-- delta -->
                <argument>${basedir}/src/main/webapp/modules/bim/assets/icons/delta</argument>
                <argument>${basedir}/target/bimrocket/modules/bim/assets/icons/delta.svg</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.2</version>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
          <webResources>
            <resource>
              <directory>${basedir}/target</directory>
              <targetPath>platform/ui</targetPath>
              <includes>
                <include>Application.js</include>
              </includes>
            </resource>
          </webResources>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>package-static</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <descriptors>
                <descriptor>src/main/assembly/static.xml</descriptor>
              </descriptors>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>